In [36]:
import pandas as pd
from datasets import load_dataset, DatasetDict, Dataset
import logging
import time
import os
import json
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report
from tqdm import tqdm
from transformers import (
    RobertaTokenizer,
    RobertaForSequenceClassification,
    TrainingArguments,
    Trainer,
    EarlyStoppingCallback,
    DataCollatorWithPadding
)
import torch.nn.functional as F
import numpy as np
import torch

In [37]:
train=pd.read_csv("/home/bmuscato/venv_b/share/doc/networkx-3.1/dataset/code_TACL/train_sum_soft.csv")
test=pd.read_csv("/home/bmuscato/venv_b/share/doc/networkx-3.1/dataset/code_TACL/test_sum_soft.csv")
val=pd.read_csv("/home/bmuscato/venv_b/share/doc/networkx-3.1/dataset/code_TACL/val_sum_soft.csv")

In [38]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")

Using device: cuda


In [39]:
from huggingface_hub import login

login(token="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")

In [40]:
model_name = 'roberta-large'
model_name_filename = model_name.replace("/", "-")

In [41]:
tokenizer = RobertaTokenizer.from_pretrained('roberta-large')

In [42]:
output_dir = f"./multiclassification_stance/{model_name_filename}/results/human"

In [43]:
num_labels=4

In [44]:
model = RobertaForSequenceClassification.from_pretrained('roberta-large', num_labels=num_labels)

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-large and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [45]:
train

Unnamed: 0.1  Unnamed: 0  QID_x                       Topic  \
0               0           0     50          Fighting in Hockey   
1               1           1     42  Prostitution - Legalize It   
2               2           2     40      Drone Strikes Overseas   
3               3           3     11       Prescription Drug Ads   
4               4           4     33               Ronald Reagan   
..            ...         ...    ...                         ...   
711           711         729     44                Social Media   
712           712         730     42  Prostitution - Legalize It   
713           713         731     13          Standardized Tests   
714           714         732     23          Concealed Handguns   
715           715         733     16              Teacher Tenure   

                                                 Query     docID  \
0                Should Fighting Be Allowed in Hockey?   2s50q1r   
1                        Should Prostitution Be Legal?   1s42q3r   
2    Should the United States Continue Its Use of D...  2s40q10r   
3    Should Prescription Drugs Be Advertised Direct...   2s11q4r   
4                  Was Ronald Reagan a Good President?   2s33q1r   
..                                                 ...       ...   
711  Are Social Networking Sites Good for Our Society?   2s44q2r   
712                      Should Prostitution Be Legal?   2s42q9r   
713  Is the Use of Standardized Tests Improving Edu...   1s13q8r   
714  Should Adults Have the Right to Carry a Concea...   2s23q5r   
715                        Should Teachers Get Tenure?   2s16q6r   

                                                docURL  \
0    https://www.nbcsports.com/washington/capitals/...   
1    https://medium.com/@nkuphirun/a-global-debate-...   
2    https://www.popmatters.com/iron-man-3-shane-bl...   
3    https://www.techtimes.com/articles/238486/2019...   
4    https://71republic.com/2019/02/16/ronald-reaga...   
..                                                 ...   
711  https://www.zmescience.com/science/native-amer...   
712  https://helenair.com/opinion/letters/this-week...   
713  https://thinkprogress.org/why-we-need-to-impro...   
714  https://www.foxnews.com/us/new-study-finds-gro...   
715  https://www.nytimes.com/2019/02/18/us/edray-go...   

                                              docTitle  \
0    Explaining the unwritten rules and etiquette o...   
1    A Global debate: Should Prostitution be Legali...   
2    'Iron Man 3' Finds Its Hero in Crisis - PopMat...   
3    J&J First Big Pharma Company To Add Prices To ...   
4        Just How Good Was Ronald Reagan As President?   
..                                                 ...   
711  Native American societies had their own brand ...   
712  This week's letters to the editor: Border wall...   
713  Why We Need To Improve Standardized Testing – ...   
714  New study finds growing demand for concealed h...   
715  For a Black Mathematician, What It’s Like to B...   

                                               docCont  engineID  ...  \
0    Lars Eller saw his target. He quickly skated o...         2  ...   
1    Human Trafficking, one of the world’s greatest...         1  ...   
2    Marvel Studios launched its second phase of fi...         2  ...   
3    This is a modal window.Johnson & Johnson has a...         2  ...   
4    In the modern-day Republican Party, Ronald Rea...         2  ...   
..                                                 ...       ...  ...   
711  Cookie NoticeWe use cookies to personalize con...         2  ...   
712  © 2019 Lee EnterprisesTerms of Service  |  Pri...         2  ...   
713  Parents who oppose standardized testing have b...         1  ...   
714  This material may not be published, broadcast,...         2  ...   
715  Fewer than 1 percent of doctorates in math are...         2  ...   

     majority_label                                   labels  \
0               Pro                 

In [ ]:

from datasets import Dataset, DatasetDict

def no_maj(df):
    return df.loc[df['majority_label'] != 'No majority']
train, test, val = map(no_maj, [train, test, val]) 


label_encoding = {'Pro': 0,
'Against': 1,
'Neutral': 2,
'Not-about': 3}

train['labels'] = train['majority_label'].map(label_encoding)
val['labels'] = val['majority_label'].map(label_encoding)
test['labels'] = test['majority_label'].map(label_encoding)
# Convert 'hard_label' column to integers to ensure consistent types
train['labels'] = train['labels'].astype(int)
test['labels'] = test['labels'].astype(int)
val['labels'] = val['labels'].astype(int)



# Convert DataFrames to Hugging Face Dataset objects
train_ = Dataset.from_pandas(train, preserve_index=False)
test_ = Dataset.from_pandas(test, preserve_index=False)
val_ = Dataset.from_pandas(val, preserve_index=False)

# Combine datasets into a DatasetDict
dataset = DatasetDict({'train': train_, 'test': test_, 'val': val_})

# Define the tokenization function
def tokenize_func(examples):
    tokenized_inputs = tokenizer(
        examples['Input'], 
        padding='max_length', 
        truncation=True, 
        max_length=512
    )
    # Add labels to the tokenized inputs
    tokenized_inputs['label'] = examples['labels']
    return tokenized_inputs

# Tokenize datasets
train_tokenized = train_.map(tokenize_func, batched=True)
val_tokenized = val_.map(tokenize_func, batched=True)
test_tokenized = test_.map(tokenize_func, batched=True)

# Convert datasets to PyTorch format
train_tokenized.set_format('torch', columns=['input_ids', 'attention_mask', 'label'])
val_tokenized.set_format('torch', columns=['input_ids', 'attention_mask', 'label'])
test_tokenized.set_format('torch', columns=['input_ids', 'attention_mask', 'label'])


/tmp/ipykernel_1972306/3627685613.py:13: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train['labels'] = train['majority_label'].map(label_encoding)
/tmp/ipykernel_1972306/3627685613.py:17: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train['labels'] = train['labels'].astype(int)
Map: 100%|██████████| 139/139 [00:00<00:00, 228.98 examples/s]


In [47]:
data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

In [48]:
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    accuracy = accuracy_score(labels, predictions)
    f1 = f1_score(labels, predictions, average='macro')
    
    # Compute cross-entropy loss
    probs = torch.nn.functional.softmax(torch.tensor(logits), dim=-1).numpy() 
    cross_entropy = -np.sum(np.eye(probs.shape[1])[labels] * np.log(probs + 1e-9)) / len(labels)
    
    return {
        'accuracy': accuracy,
        'f1': f1,
        'cross_entropy': cross_entropy
    }

In [49]:
training_args = TrainingArguments(
    output_dir=output_dir,
    num_train_epochs=8,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    warmup_steps=500,
    weight_decay=0.01,
    logging_dir="./logs",
    logging_steps=10,
    learning_rate=5e-5,
    evaluation_strategy="epoch",
    save_strategy="epoch",
    metric_for_best_model="eval_f1",
    load_best_model_at_end=True,
)

/home/bmuscato/venv_b/lib/python3.8/site-packages/transformers/training_args.py:1568: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(


In [50]:
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_tokenized,
    eval_dataset=train_tokenized,
    tokenizer=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=3)]
)

/tmp/ipykernel_1972306/2340046930.py:1: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.


In [51]:
trainer.train()

/home/bmuscato/venv_b/lib/python3.8/site-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '


/home/bmuscato/venv_b/lib/python3.8/site-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '
/home/bmuscato/venv_b/lib/python3.8/site-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '
/home/bmuscato/venv_b/lib/python3.8/site-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '
/home/bmuscato/venv_b/lib/python3.8/site-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all in

TrainOutput(global_step=160, training_loss=1.1277449488639832, metrics={'train_runtime': 507.9958, 'train_samples_per_second': 9.748, 'train_steps_per_second': 0.315, 'total_flos': 4614955296915456.0, 'train_loss': 1.1277449488639832, 'epoch': 8.0})

In [52]:
eval_results = trainer.evaluate()
print(eval_results)

/home/bmuscato/venv_b/lib/python3.8/site-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '


{'eval_loss': 0.4322259724140167, 'eval_accuracy': 0.8481421647819063, 'eval_f1': 0.8478538324420677, 'eval_cross_entropy': 0.4322192390089755, 'eval_runtime': 14.4335, 'eval_samples_per_second': 42.886, 'eval_steps_per_second': 1.386, 'epoch': 8.0}


In [53]:
best_model_dir = f'{output_dir}/best_model'

In [54]:
model.push_to_hub("bmuscato/baseline_stance")
tokenizer.push_to_hub("bmuscato/baseline_stance") 

model.safetensors: 100%|██████████| 1.42G/1.42G [00:46<00:00, 30.6MB/s]


CommitInfo(commit_url='https://huggingface.co/bmuscato/baseline_stance/commit/313caaa6e9ed5a2345cb57400bd12db9621b4ff6', commit_message='Upload tokenizer', commit_description='', oid='313caaa6e9ed5a2345cb57400bd12db9621b4ff6', pr_url=None, repo_url=RepoUrl('https://huggingface.co/bmuscato/baseline_stance', endpoint='https://huggingface.co', repo_type='model', repo_id='bmuscato/baseline_stance'), pr_revision=None, pr_num=None)

In [55]:

model.to(device)
model.eval()

RobertaForSequenceClassification(
  (roberta): RobertaModel(
    (embeddings): RobertaEmbeddings(
      (word_embeddings): Embedding(50265, 1024, padding_idx=1)
      (position_embeddings): Embedding(514, 1024, padding_idx=1)
      (token_type_embeddings): Embedding(1, 1024)
      (LayerNorm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): RobertaEncoder(
      (layer): ModuleList(
        (0-23): 24 x RobertaLayer(
          (attention): RobertaAttention(
            (self): RobertaSdpaSelfAttention(
              (query): Linear(in_features=1024, out_features=1024, bias=True)
              (key): Linear(in_features=1024, out_features=1024, bias=True)
              (value): Linear(in_features=1024, out_features=1024, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): RobertaSelfOutput(
              (dense): Linear(in_features=1024, out_features=1024, bias=Tru

In [56]:
def calculate_confidences(df, model, tokenizer):
    confidences = []
    model.eval()  # Set model to evaluation mode

    for text in df['Input']:
        # Tokenize and preprocess the text input
        inputs = tokenizer(text, return_tensors="pt", truncation=True, padding=True)

        
        with torch.no_grad():
            logits = model(**inputs).logits
            probabilities = torch.nn.functional.softmax(logits, dim=-1)  # Convert logits to probabilities
            confidences.append(probabilities.max().item())  # Max confidence for the predicted class
    
    df['confidence_scores'] = confidences
    return df

In [57]:
def predictions(text):
    inputs = tokenizer(text, return_tensors="pt", truncation = True, padding = 'max_length', max_length = 512).to(device)
    with torch.no_grad():
        logits = model(**inputs).logits
        probabilities = torch.nn.functional.softmax(logits, dim=-1).tolist()[0]
        predicted_class = np.argmax(probabilities)
        return probabilities, predicted_class

In [58]:
softmax_prob = []
softmax_pred = []

for i, row in test.iterrows():
    text = row['Input']
    probs, preds = predictions(text)
    softmax_prob.append(probs)
    softmax_pred.append(preds)

In [59]:
test['softmax_prob'] = softmax_prob
test['softmax_preds'] = softmax_pred

In [60]:
y_true = test['labels'] 
y_pred = test['softmax_preds']

y_true = [int(label) for label in y_true]  
y_pred = [int(label) for label in y_pred]

# Accuracy
accuracy = accuracy_score(y_true, y_pred)
print("Accuracy:", accuracy*100)

# Precision
precision = precision_score(y_true, y_pred, average='macro')  # 'macro' averaging for multiclass
print("Precision:", precision*100)

# Recall
recall = recall_score(y_true, y_pred, average='macro')  # 'macro' averaging for multiclass
print("Recall:", recall*100)

# F1 Score
f1 = f1_score(y_true, y_pred, average='macro')  # 'macro' averaging for multiclass
print("F1 Score:", f1*100)

# Confusion Matrix
conf_matrix = confusion_matrix(y_true, y_pred)
print("Confusion Matrix:")
print(conf_matrix)

# Classification Report
class_report = classification_report(y_true, y_pred)
print("Classification Report:")
print(class_report)

Accuracy: 46.76258992805755
Precision: 56.05273752012883
Recall: 44.997995188452286
F1 Score: 45.614236681480556
Confusion Matrix:
[[19  0 20  4]
 [ 0  6 22  1]
 [ 6  3 28  6]
 [ 2  0 10 12]]
Classification Report:
              precision    recall  f1-score   support

           0       0.70      0.44      0.54        43
           1       0.67      0.21      0.32        29
           2       0.35      0.65      0.46        43
           3       0.52      0.50      0.51        24

    accuracy                           0.47       139
   macro avg       0.56      0.45      0.46       139
weighted avg       0.56      0.47      0.46       139



In [61]:
def calculate_confidences(df, model, tokenizer):
    confidences = []
    model.eval()  # Set model to evaluation mode

    for text in df['Input']:
        # Tokenize and preprocess the text input
        inputs = tokenizer(text, return_tensors="pt", truncation=True, padding=True).to(model.device)
        
        with torch.no_grad():
            logits = model(**inputs).logits
            probabilities = torch.nn.functional.softmax(logits, dim=-1)  # Convert logits to probabilities
            confidences.append(probabilities.max().item())  # Max confidence for the predicted class
    
    df['confidence_scores'] = confidences
    return df

In [62]:
test_df = calculate_confidences(test, model, tokenizer)
confidence_scores = test['confidence_scores']

    # Confidence for Correct and Incorrect Predictions
correct_confidence = np.mean([confidence for pred, true, confidence in zip(y_pred, y_true, confidence_scores) if pred == true])
incorrect_confidence = np.mean([confidence for pred, true, confidence in zip(y_pred, y_true, confidence_scores) if pred != true])

avg_confidence = np.mean(confidence_scores)
print("Average Confidence Score:", avg_confidence * 100)

print("Average Confidence for Correct Predictions:", correct_confidence * 100)
print("Average Confidence for Incorrect Predictions:", incorrect_confidence * 100)

Average Confidence Score: 70.48201290823573
Average Confidence for Correct Predictions: 73.23887265645541
Average Confidence for Incorrect Predictions: 68.06044691317791


In [63]:
test.to_csv("/home/bmuscato/venv_b/share/doc/networkx-3.1/dataset/code_TACL/results_roberta_baseline_f1m_stance.csv")